[book]
authors = ["Ben Falk"]
language = "en"
multilingual = false
src = "src"
title = "Tickets Example"

[preprocessor.journal.topics.ticket]
path_mapping = "%Y-%m/{{ticket_number}}-{{kebabCase title}}"
template = """

## {{titleCase title}}
"""
leaf_template = """
# {{path}}

| Ticket # | Title |
|----------|-------|
{{#each entries}}
| [{{this.meta.ticket_number}}] | {{this.meta.title}} |
{{/each}}

{{#each entries}}
  [{{this.meta.ticket_number}}]: /{{this.virtual_path}}
{{/each}}
"""
[preprocessor.journal.topics.ticket.variables]
title = { required = true }
ticket_number = { required = true }
category = { required = true }
